//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnDProject {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DnDProject.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //Name,diceRolled,hitDie,STR,DEX,CON,INT,WIS,CHR,page#,SkillList
        ///Aarakocra,3,8,10,14,10,11,12,11,12,Bite-Javelin
        ///Aboleth,18,10,21,9,15,18,15,18,13,Tentacle-Tail
        ///Abominable Yeti,11,12,24,10,22,9,13,9,306,Multiattack-Claw-Chilling Gaze-Cold Breath
        ///Acolyte,2,8,10,10,10,10,14,11,342,Club
        ///Adult Black Dragon,17,12,23,14,21,14,13,17,88,Multiattack-Bite-Claw-Tail-Frightful Presence-Acid Breath
        ///Adult Blue Dracolich,18,12,25,10,23,16,15,19,84
        ///Adult Blue Dragon,18,12,25,10,23,16,15,19,91
        ///Adult Brass Dragon,15, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MonsterList {
            get {
                return ResourceManager.GetString("MonsterList", resourceCulture);
            }
        }
    }
}
